version: "3.9"

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: quantdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  worker:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: quant-worker
    command: >
      celery -A task_manager.celery_app worker
      --loglevel=info
      --queues=io_intensive,cpu,celery
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      DB_URL: postgresql+psycopg://admin:123456@postgres:5432/quantdb  # ä¿®æ”¹è¿™é‡Œ
    depends_on:
      - redis
      - postgres
    volumes:
      - ../src:/app/src
      - ../data/config:/app/data/config
      - ../data/tick_test:/app/data/tick_test

  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: quant-api
    command: [ "python", "-m", "crypto_data_engine.main","start" ]
    ports:
      - "8080:8080"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DB_URL=postgresql+psycopg://admin:123456@postgres:1234/quantdb
    depends_on:
      - redis
      - postgres
    volumes:
      - ../src:/app/src
      - ../data/config:/app/data/config





  # ğŸ”¥ Flower ç›‘æ§æœåŠ¡

  flower:
    image: mher/flower:2.0.1
    container_name: quant-flower
    command: ["celery", "--broker=redis://redis:6379/0", "flower","--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
    restart: unless-stopped


volumes:
  redis_data:
  pg_data: